### PR TITLE
Add missing macos target with "flutter create ."

### PR DESCRIPTION
**Pull request by nickmeinhold**
Maybe there was a reason to not include the macos target?  The app ran fine for me as a macos app. Thanks!

### CODE REVIEW

**Comment by hanskokx** [comment]
I think it wasn't created because nobody who has a mac created it XD

**Review by hanskokx — CHANGES_REQUESTED** [review]
Generated files should not be included.
- GeneratedPluginRegistrant.swift
- Podfile.lock
-

**Comment by nickmeinhold** [comment]
I just used "flutter create" and nothing else changed so I guess you're arguing that the .gitignore that comes with "flutter create" should be changed?  I would agree with a slightly less strong statement such as "Generated files *generally* should not be included." but there are certainly exceptions to "Generated files should not be included." right?  The .lock files are a good example where it's generally agreed (as far as I can tell) that ignoring the .lock files is desirable for package projects (where you want loose constraints for version solving) and not for app projects (for various reasons including consistent CI environments). Anyway happy to debate these individual instances - the .lock files I would argue for keeping in version control, the GeneratedPluginRegistrant.swift I'd have to look into to have an opinion but overall it seems easier to just go with the default choices made by the Flutter team to me... what do you think?

**Comment by hanskokx** [comment]
🤷🏼‍♂️

**Pull request merged**
